#!/bin/bash


_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Rep" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3JvZ2VycHEvUmVwdGhvbkFyL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3JvZ2VycHEvUmVwdGhvbkFyL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Rep" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3JvZ2VycHEvUmVwdGhvbkFyLmdpdA==" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3JvZ2VycHEvUmVwdGhvbkFyLmdpdA==" | base64 -d`
    fi
    echo "$rlink"
}

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_catpack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/rogerpq/RepthonAr"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_cat_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    echo "-----> Installing p7zip"
    BUILD_DIR=$1
    mkdir -p "$BUILD_DIR/vendor"
    VENDOR_DIR="$BUILD_DIR/vendor"
    curl "https://raw.githubusercontent.com/riganf/heroku-buildpack-p7zip/master/p7zip.tar.gz" -s -o - | tar xzf - -C "$VENDOR_DIR"
    chmod 777 "$VENDOR_DIR/p7zip"
    chmod 777 "$VENDOR_DIR/p7zip/bin/7zz"
    PROFILE_PATH="$BUILD_DIR/.profile.d/7zz.sh"
    mkdir -p $(dirname $PROFILE_PATH)
    python3 setup/updater.py requirements.txt requirements.txt
    local zippath
    zippath="RepthonAr.zip"
    echo "جار تنزيل مكاتب السورس ✓"
    wget -q $(_get_ziplink) -O "$zippath"
    echo " يتم الان تفريغ بيانات ريبثون "
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "✓ تم التفريغ "
    echo " يتم التنظيف "
    rm -rf "$zippath"
    sleep 5
    _run_catpack_git
    cd $CATPATH
    _run_cat_git
    python3 setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "   ᯽︙ جارِ بدء سورس ريبثون    "
    echo "
    "
    python3 -m jepthon
}

_set_bot
